// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/tag-photo-bibs/handler (interfaces: BibIndexStore)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/racephotos/shared/models"
)

// MockBibIndexStore is a mock of BibIndexStore interface.
type MockBibIndexStore struct {
	ctrl     *gomock.Controller
	recorder *MockBibIndexStoreMockRecorder
}

// MockBibIndexStoreMockRecorder is the mock recorder for MockBibIndexStore.
type MockBibIndexStoreMockRecorder struct {
	mock *MockBibIndexStore
}

// NewMockBibIndexStore creates a new mock instance.
func NewMockBibIndexStore(ctrl *gomock.Controller) *MockBibIndexStore {
	mock := &MockBibIndexStore{ctrl: ctrl}
	mock.recorder = &MockBibIndexStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBibIndexStore) EXPECT() *MockBibIndexStoreMockRecorder {
	return m.recorder
}

// DeleteBibEntriesByPhoto mocks base method.
func (m *MockBibIndexStore) DeleteBibEntriesByPhoto(ctx context.Context, photoID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBibEntriesByPhoto", ctx, photoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBibEntriesByPhoto indicates an expected call of DeleteBibEntriesByPhoto.
func (mr *MockBibIndexStoreMockRecorder) DeleteBibEntriesByPhoto(ctx, photoID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBibEntriesByPhoto", reflect.TypeOf((*MockBibIndexStore)(nil).DeleteBibEntriesByPhoto), ctx, photoID)
}

// WriteBibEntries mocks base method.
func (m *MockBibIndexStore) WriteBibEntries(ctx context.Context, entries []models.BibEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBibEntries", ctx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteBibEntries indicates an expected call of WriteBibEntries.
func (mr *MockBibIndexStoreMockRecorder) WriteBibEntries(ctx, entries interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBibEntries", reflect.TypeOf((*MockBibIndexStore)(nil).WriteBibEntries), ctx, entries)
}
