// Code generated by MockGen. DO NOT EDIT.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/racephotos/shared/models"
)

// MockEventStore is a mock of EventStore interface.
type MockEventStore struct {
	ctrl     *gomock.Controller
	recorder *MockEventStoreMockRecorder
}

// MockEventStoreMockRecorder is the mock recorder for MockEventStore.
type MockEventStoreMockRecorder struct {
	mock *MockEventStore
}

// NewMockEventStore creates a new mock instance.
func NewMockEventStore(ctrl *gomock.Controller) *MockEventStore {
	mock := &MockEventStore{ctrl: ctrl}
	mock.recorder = &MockEventStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStore) EXPECT() *MockEventStoreMockRecorder {
	return m.recorder
}

// ListActiveEvents mocks base method.
func (m *MockEventStore) ListActiveEvents(ctx context.Context, cursor string, limit int) ([]models.Event, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveEvents", ctx, cursor, limit)
	ret0, _ := ret[0].([]models.Event)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListActiveEvents indicates an expected call of ListActiveEvents.
func (mr *MockEventStoreMockRecorder) ListActiveEvents(ctx, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"ListActiveEvents",
		reflect.TypeOf((*MockEventStore)(nil).ListActiveEvents),
		ctx, cursor, limit,
	)
}
