// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/archive-event/handler (interfaces: EventArchiver)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	models "github.com/racephotos/shared/models"
)

// MockEventArchiver is a mock of EventArchiver interface.
type MockEventArchiver struct {
	ctrl     *gomock.Controller
	recorder *MockEventArchiverMockRecorder
}

// MockEventArchiverMockRecorder is the mock recorder for MockEventArchiver.
type MockEventArchiverMockRecorder struct {
	mock *MockEventArchiver
}

// NewMockEventArchiver creates a new mock instance.
func NewMockEventArchiver(ctrl *gomock.Controller) *MockEventArchiver {
	mock := &MockEventArchiver{ctrl: ctrl}
	mock.recorder = &MockEventArchiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventArchiver) EXPECT() *MockEventArchiverMockRecorder {
	return m.recorder
}

// ArchiveEvent mocks base method.
func (m *MockEventArchiver) ArchiveEvent(ctx context.Context, id, callerID string) (*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveEvent", ctx, id, callerID)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArchiveEvent indicates an expected call of ArchiveEvent.
func (mr *MockEventArchiverMockRecorder) ArchiveEvent(ctx, id, callerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveEvent",
		reflect.TypeOf((*MockEventArchiver)(nil).ArchiveEvent), ctx, id, callerID)
}
