// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/list-public-event-photos/handler (interfaces: EventPhotoLister)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/racephotos/shared/models"
)

// MockEventPhotoLister is a mock of EventPhotoLister interface.
type MockEventPhotoLister struct {
	ctrl     *gomock.Controller
	recorder *MockEventPhotoListerMockRecorder
}

// MockEventPhotoListerMockRecorder is the mock recorder for MockEventPhotoLister.
type MockEventPhotoListerMockRecorder struct {
	mock *MockEventPhotoLister
}

// NewMockEventPhotoLister creates a new mock instance.
func NewMockEventPhotoLister(ctrl *gomock.Controller) *MockEventPhotoLister {
	mock := &MockEventPhotoLister{ctrl: ctrl}
	mock.recorder = &MockEventPhotoListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPhotoLister) EXPECT() *MockEventPhotoListerMockRecorder {
	return m.recorder
}

// ListEventPhotos mocks base method.
func (m *MockEventPhotoLister) ListEventPhotos(ctx context.Context, eventID, cursor string, limit int) ([]models.Photo, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEventPhotos", ctx, eventID, cursor, limit)
	ret0, _ := ret[0].([]models.Photo)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEventPhotos indicates an expected call of ListEventPhotos.
func (mr *MockEventPhotoListerMockRecorder) ListEventPhotos(ctx, eventID, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEventPhotos",
		reflect.TypeOf((*MockEventPhotoLister)(nil).ListEventPhotos), ctx, eventID, cursor, limit)
}
