// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/list-public-event-photos/handler (interfaces: PublicEventReader)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/racephotos/shared/models"
)

// MockPublicEventReader is a mock of PublicEventReader interface.
type MockPublicEventReader struct {
	ctrl     *gomock.Controller
	recorder *MockPublicEventReaderMockRecorder
}

// MockPublicEventReaderMockRecorder is the mock recorder for MockPublicEventReader.
type MockPublicEventReaderMockRecorder struct {
	mock *MockPublicEventReader
}

// NewMockPublicEventReader creates a new mock instance.
func NewMockPublicEventReader(ctrl *gomock.Controller) *MockPublicEventReader {
	mock := &MockPublicEventReader{ctrl: ctrl}
	mock.recorder = &MockPublicEventReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicEventReader) EXPECT() *MockPublicEventReaderMockRecorder {
	return m.recorder
}

// GetPublicEvent mocks base method.
func (m *MockPublicEventReader) GetPublicEvent(ctx context.Context, eventID string) (*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicEvent", ctx, eventID)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicEvent indicates an expected call of GetPublicEvent.
func (mr *MockPublicEventReaderMockRecorder) GetPublicEvent(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicEvent",
		reflect.TypeOf((*MockPublicEventReader)(nil).GetPublicEvent), ctx, eventID)
}
