// Code generated by MockGen. DO NOT EDIT.
// Source: handler (interfaces: PurchaseStore,OrderStore)
package mocks

import (
	"context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/racephotos/shared/models"
)

// MockPurchaseStore is a mock of PurchaseStore interface.
type MockPurchaseStore struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseStoreMockRecorder
}

type MockPurchaseStoreMockRecorder struct {
	mock *MockPurchaseStore
}

func NewMockPurchaseStore(ctrl *gomock.Controller) *MockPurchaseStore {
	mock := &MockPurchaseStore{ctrl: ctrl}
	mock.recorder = &MockPurchaseStoreMockRecorder{mock}
	return mock
}

func (m *MockPurchaseStore) EXPECT() *MockPurchaseStoreMockRecorder {
	return m.recorder
}

func (m *MockPurchaseStore) GetPurchase(ctx context.Context, id string) (*models.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchase", ctx, id)
	ret0, _ := ret[0].(*models.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPurchaseStoreMockRecorder) GetPurchase(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchase", reflect.TypeOf((*MockPurchaseStore)(nil).GetPurchase), ctx, id)
}

func (m *MockPurchaseStore) QueryPurchasesByOrder(ctx context.Context, orderID string) ([]*models.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryPurchasesByOrder", ctx, orderID)
	ret0, _ := ret[0].([]*models.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPurchaseStoreMockRecorder) QueryPurchasesByOrder(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryPurchasesByOrder", reflect.TypeOf((*MockPurchaseStore)(nil).QueryPurchasesByOrder), ctx, orderID)
}

func (m *MockPurchaseStore) UpdatePurchaseRejected(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePurchaseRejected", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockPurchaseStoreMockRecorder) UpdatePurchaseRejected(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePurchaseRejected", reflect.TypeOf((*MockPurchaseStore)(nil).UpdatePurchaseRejected), ctx, id)
}

// MockOrderStore is a mock of OrderStore interface.
type MockOrderStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrderStoreMockRecorder
}

type MockOrderStoreMockRecorder struct {
	mock *MockOrderStore
}

func NewMockOrderStore(ctrl *gomock.Controller) *MockOrderStore {
	mock := &MockOrderStore{ctrl: ctrl}
	mock.recorder = &MockOrderStoreMockRecorder{mock}
	return mock
}

func (m *MockOrderStore) EXPECT() *MockOrderStoreMockRecorder {
	return m.recorder
}

func (m *MockOrderStore) GetOrder(ctx context.Context, id string) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, id)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockOrderStoreMockRecorder) GetOrder(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrderStore)(nil).GetOrder), ctx, id)
}

func (m *MockOrderStore) UpdateOrderStatus(ctx context.Context, id, status, updatedAt string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, id, status, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockOrderStoreMockRecorder) UpdateOrderStatus(ctx, id, status, updatedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderStore)(nil).UpdateOrderStatus), ctx, id, status, updatedAt)
}
