// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/create-order/handler (interfaces: EmailSender)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// SendTemplatedEmail mocks base method.
func (m *MockEmailSender) SendTemplatedEmail(ctx context.Context, to, template string, data map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTemplatedEmail", ctx, to, template, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTemplatedEmail indicates an expected call of SendTemplatedEmail.
func (mr *MockEmailSenderMockRecorder) SendTemplatedEmail(ctx, to, template, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTemplatedEmail",
		reflect.TypeOf((*MockEmailSender)(nil).SendTemplatedEmail), ctx, to, template, data)
}
