// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/create-order/handler (interfaces: OrderTransacter)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/racephotos/shared/models"
)

// MockOrderTransacter is a mock of OrderTransacter interface.
type MockOrderTransacter struct {
	ctrl     *gomock.Controller
	recorder *MockOrderTransacterMockRecorder
}

// MockOrderTransacterMockRecorder is the mock recorder for MockOrderTransacter.
type MockOrderTransacterMockRecorder struct {
	mock *MockOrderTransacter
}

// NewMockOrderTransacter creates a new mock instance.
func NewMockOrderTransacter(ctrl *gomock.Controller) *MockOrderTransacter {
	mock := &MockOrderTransacter{ctrl: ctrl}
	mock.recorder = &MockOrderTransacterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderTransacter) EXPECT() *MockOrderTransacterMockRecorder {
	return m.recorder
}

// CreateOrderWithPurchases mocks base method.
func (m *MockOrderTransacter) CreateOrderWithPurchases(ctx context.Context, order models.Order, purchases []models.Purchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderWithPurchases", ctx, order, purchases)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrderWithPurchases indicates an expected call of CreateOrderWithPurchases.
func (mr *MockOrderTransacterMockRecorder) CreateOrderWithPurchases(ctx, order, purchases interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderWithPurchases",
		reflect.TypeOf((*MockOrderTransacter)(nil).CreateOrderWithPurchases), ctx, order, purchases)
}
