// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/create-order/handler (interfaces: PhotographerStore)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/racephotos/shared/models"
)

// MockPhotographerStore is a mock of PhotographerStore interface.
type MockPhotographerStore struct {
	ctrl     *gomock.Controller
	recorder *MockPhotographerStoreMockRecorder
}

// MockPhotographerStoreMockRecorder is the mock recorder for MockPhotographerStore.
type MockPhotographerStoreMockRecorder struct {
	mock *MockPhotographerStore
}

// NewMockPhotographerStore creates a new mock instance.
func NewMockPhotographerStore(ctrl *gomock.Controller) *MockPhotographerStore {
	mock := &MockPhotographerStore{ctrl: ctrl}
	mock.recorder = &MockPhotographerStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotographerStore) EXPECT() *MockPhotographerStoreMockRecorder {
	return m.recorder
}

// GetPhotographer mocks base method.
func (m *MockPhotographerStore) GetPhotographer(ctx context.Context, id string) (*models.Photographer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotographer", ctx, id)
	ret0, _ := ret[0].(*models.Photographer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotographer indicates an expected call of GetPhotographer.
func (mr *MockPhotographerStoreMockRecorder) GetPhotographer(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotographer",
		reflect.TypeOf((*MockPhotographerStore)(nil).GetPhotographer), ctx, id)
}
