// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/create-order/handler (interfaces: PurchaseStore)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/racephotos/shared/models"
)

// MockPurchaseStore is a mock of PurchaseStore interface.
type MockPurchaseStore struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseStoreMockRecorder
}

// MockPurchaseStoreMockRecorder is the mock recorder for MockPurchaseStore.
type MockPurchaseStoreMockRecorder struct {
	mock *MockPurchaseStore
}

// NewMockPurchaseStore creates a new mock instance.
func NewMockPurchaseStore(ctrl *gomock.Controller) *MockPurchaseStore {
	mock := &MockPurchaseStore{ctrl: ctrl}
	mock.recorder = &MockPurchaseStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseStore) EXPECT() *MockPurchaseStoreMockRecorder {
	return m.recorder
}

// GetPurchaseByPhotoAndEmail mocks base method.
func (m *MockPurchaseStore) GetPurchaseByPhotoAndEmail(ctx context.Context, photoID, runnerEmail string) (*models.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchaseByPhotoAndEmail", ctx, photoID, runnerEmail)
	ret0, _ := ret[0].(*models.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchaseByPhotoAndEmail indicates an expected call of GetPurchaseByPhotoAndEmail.
func (mr *MockPurchaseStoreMockRecorder) GetPurchaseByPhotoAndEmail(ctx, photoID, runnerEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchaseByPhotoAndEmail",
		reflect.TypeOf((*MockPurchaseStore)(nil).GetPurchaseByPhotoAndEmail), ctx, photoID, runnerEmail)
}
