// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/get-event/handler (interfaces: EventGetter)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/racephotos/shared/models"
)

// MockEventGetter is a mock of EventGetter interface.
type MockEventGetter struct {
	ctrl     *gomock.Controller
	recorder *MockEventGetterMockRecorder
}

// MockEventGetterMockRecorder is the mock recorder for MockEventGetter.
type MockEventGetterMockRecorder struct {
	mock *MockEventGetter
}

// NewMockEventGetter creates a new mock instance.
func NewMockEventGetter(ctrl *gomock.Controller) *MockEventGetter {
	mock := &MockEventGetter{ctrl: ctrl}
	mock.recorder = &MockEventGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventGetter) EXPECT() *MockEventGetterMockRecorder {
	return m.recorder
}

// GetEvent mocks base method.
func (m *MockEventGetter) GetEvent(ctx context.Context, id string) (*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", ctx, id)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockEventGetterMockRecorder) GetEvent(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent",
		reflect.TypeOf((*MockEventGetter)(nil).GetEvent), ctx, id)
}
