// Code generated by MockGen. DO NOT EDIT.
// Source: handler (interfaces: PurchaseStore,RateLimitStore,EmailSender)
package mocks

import (
	"context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/racephotos/shared/models"
)

// MockPurchaseStore is a mock of PurchaseStore interface.
type MockPurchaseStore struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseStoreMockRecorder
}

type MockPurchaseStoreMockRecorder struct {
	mock *MockPurchaseStore
}

func NewMockPurchaseStore(ctrl *gomock.Controller) *MockPurchaseStore {
	mock := &MockPurchaseStore{ctrl: ctrl}
	mock.recorder = &MockPurchaseStoreMockRecorder{mock}
	return mock
}

func (m *MockPurchaseStore) EXPECT() *MockPurchaseStoreMockRecorder {
	return m.recorder
}

func (m *MockPurchaseStore) GetApprovedPurchasesByEmail(ctx context.Context, email string) ([]models.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApprovedPurchasesByEmail", ctx, email)
	ret0, _ := ret[0].([]models.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPurchaseStoreMockRecorder) GetApprovedPurchasesByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApprovedPurchasesByEmail", reflect.TypeOf((*MockPurchaseStore)(nil).GetApprovedPurchasesByEmail), ctx, email)
}

// MockRateLimitStore is a mock of RateLimitStore interface.
type MockRateLimitStore struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimitStoreMockRecorder
}

type MockRateLimitStoreMockRecorder struct {
	mock *MockRateLimitStore
}

func NewMockRateLimitStore(ctrl *gomock.Controller) *MockRateLimitStore {
	mock := &MockRateLimitStore{ctrl: ctrl}
	mock.recorder = &MockRateLimitStoreMockRecorder{mock}
	return mock
}

func (m *MockRateLimitStore) EXPECT() *MockRateLimitStoreMockRecorder {
	return m.recorder
}

func (m *MockRateLimitStore) IncrementAndCheck(ctx context.Context, key string, windowSeconds int, limit int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAndCheck", ctx, key, windowSeconds, limit)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRateLimitStoreMockRecorder) IncrementAndCheck(ctx, key, windowSeconds, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAndCheck", reflect.TypeOf((*MockRateLimitStore)(nil).IncrementAndCheck), ctx, key, windowSeconds, limit)
}

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
}

type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

func (m *MockEmailSender) SendTemplatedEmail(ctx context.Context, to, template string, data map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTemplatedEmail", ctx, to, template, data)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEmailSenderMockRecorder) SendTemplatedEmail(ctx, to, template, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTemplatedEmail", reflect.TypeOf((*MockEmailSender)(nil).SendTemplatedEmail), ctx, to, template, data)
}
