// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/update-event/handler (interfaces: EventUpdater)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	handler "github.com/racephotos/update-event/handler"
	models "github.com/racephotos/shared/models"
)

// MockEventUpdater is a mock of EventUpdater interface.
type MockEventUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockEventUpdaterMockRecorder
}

// MockEventUpdaterMockRecorder is the mock recorder for MockEventUpdater.
type MockEventUpdaterMockRecorder struct {
	mock *MockEventUpdater
}

// NewMockEventUpdater creates a new mock instance.
func NewMockEventUpdater(ctrl *gomock.Controller) *MockEventUpdater {
	mock := &MockEventUpdater{ctrl: ctrl}
	mock.recorder = &MockEventUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventUpdater) EXPECT() *MockEventUpdaterMockRecorder {
	return m.recorder
}

// UpdateEvent mocks base method.
func (m *MockEventUpdater) UpdateEvent(ctx context.Context, id, callerID string, fields handler.UpdateFields) (*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", ctx, id, callerID, fields)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockEventUpdaterMockRecorder) UpdateEvent(ctx, id, callerID, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent",
		reflect.TypeOf((*MockEventUpdater)(nil).UpdateEvent), ctx, id, callerID, fields)
}
