// Code generated by MockGen. DO NOT EDIT.
// Source: handler (interfaces: OrderStore,PurchaseStore,PhotoStore)
package mocks

import (
	"context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/racephotos/shared/models"
)

// MockOrderStore is a mock of OrderStore interface.
type MockOrderStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrderStoreMockRecorder
}

// MockOrderStoreMockRecorder is the mock recorder for MockOrderStore.
type MockOrderStoreMockRecorder struct {
	mock *MockOrderStore
}

// NewMockOrderStore creates a new mock instance.
func NewMockOrderStore(ctrl *gomock.Controller) *MockOrderStore {
	mock := &MockOrderStore{ctrl: ctrl}
	mock.recorder = &MockOrderStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderStore) EXPECT() *MockOrderStoreMockRecorder {
	return m.recorder
}

// QueryPendingOrdersByPhotographer mocks base method.
func (m *MockOrderStore) QueryPendingOrdersByPhotographer(ctx context.Context, photographerID string) ([]*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryPendingOrdersByPhotographer", ctx, photographerID)
	ret0, _ := ret[0].([]*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryPendingOrdersByPhotographer indicates an expected call.
func (mr *MockOrderStoreMockRecorder) QueryPendingOrdersByPhotographer(ctx, photographerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryPendingOrdersByPhotographer", reflect.TypeOf((*MockOrderStore)(nil).QueryPendingOrdersByPhotographer), ctx, photographerID)
}

// MockPurchaseStore is a mock of PurchaseStore interface.
type MockPurchaseStore struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseStoreMockRecorder
}

// MockPurchaseStoreMockRecorder is the mock recorder for MockPurchaseStore.
type MockPurchaseStoreMockRecorder struct {
	mock *MockPurchaseStore
}

// NewMockPurchaseStore creates a new mock instance.
func NewMockPurchaseStore(ctrl *gomock.Controller) *MockPurchaseStore {
	mock := &MockPurchaseStore{ctrl: ctrl}
	mock.recorder = &MockPurchaseStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseStore) EXPECT() *MockPurchaseStoreMockRecorder {
	return m.recorder
}

// QueryPurchasesByOrder mocks base method.
func (m *MockPurchaseStore) QueryPurchasesByOrder(ctx context.Context, orderID string) ([]*models.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryPurchasesByOrder", ctx, orderID)
	ret0, _ := ret[0].([]*models.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryPurchasesByOrder indicates an expected call.
func (mr *MockPurchaseStoreMockRecorder) QueryPurchasesByOrder(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryPurchasesByOrder", reflect.TypeOf((*MockPurchaseStore)(nil).QueryPurchasesByOrder), ctx, orderID)
}

// MockPhotoStore is a mock of PhotoStore interface.
type MockPhotoStore struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoStoreMockRecorder
}

// MockPhotoStoreMockRecorder is the mock recorder for MockPhotoStore.
type MockPhotoStoreMockRecorder struct {
	mock *MockPhotoStore
}

// NewMockPhotoStore creates a new mock instance.
func NewMockPhotoStore(ctrl *gomock.Controller) *MockPhotoStore {
	mock := &MockPhotoStore{ctrl: ctrl}
	mock.recorder = &MockPhotoStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotoStore) EXPECT() *MockPhotoStoreMockRecorder {
	return m.recorder
}

// BatchGetPhotos mocks base method.
func (m *MockPhotoStore) BatchGetPhotos(ctx context.Context, photoIDs []string) ([]*models.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetPhotos", ctx, photoIDs)
	ret0, _ := ret[0].([]*models.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetPhotos indicates an expected call.
func (mr *MockPhotoStoreMockRecorder) BatchGetPhotos(ctx, photoIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetPhotos", reflect.TypeOf((*MockPhotoStore)(nil).BatchGetPhotos), ctx, photoIDs)
}
