// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/create-event/handler (interfaces: PhotographerReader)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	models "github.com/racephotos/shared/models"
)

// MockPhotographerReader is a mock of PhotographerReader interface.
type MockPhotographerReader struct {
	ctrl     *gomock.Controller
	recorder *MockPhotographerReaderMockRecorder
}

// MockPhotographerReaderMockRecorder is the mock recorder for MockPhotographerReader.
type MockPhotographerReaderMockRecorder struct {
	mock *MockPhotographerReader
}

// NewMockPhotographerReader creates a new mock instance.
func NewMockPhotographerReader(ctrl *gomock.Controller) *MockPhotographerReader {
	mock := &MockPhotographerReader{ctrl: ctrl}
	mock.recorder = &MockPhotographerReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotographerReader) EXPECT() *MockPhotographerReaderMockRecorder {
	return m.recorder
}

// GetPhotographer mocks base method.
func (m *MockPhotographerReader) GetPhotographer(ctx context.Context, id string) (*models.Photographer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotographer", ctx, id)
	ret0, _ := ret[0].(*models.Photographer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotographer indicates an expected call of GetPhotographer.
func (mr *MockPhotographerReaderMockRecorder) GetPhotographer(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotographer",
		reflect.TypeOf((*MockPhotographerReader)(nil).GetPhotographer), ctx, id)
}
