// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/list-event-photos/handler (interfaces: PhotoStore)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	models "github.com/racephotos/shared/models"
)

// MockPhotoStore is a mock of PhotoStore interface.
type MockPhotoStore struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoStoreMockRecorder
}

// MockPhotoStoreMockRecorder is the mock recorder for MockPhotoStore.
type MockPhotoStoreMockRecorder struct {
	mock *MockPhotoStore
}

// NewMockPhotoStore creates a new mock instance.
func NewMockPhotoStore(ctrl *gomock.Controller) *MockPhotoStore {
	mock := &MockPhotoStore{ctrl: ctrl}
	mock.recorder = &MockPhotoStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotoStore) EXPECT() *MockPhotoStoreMockRecorder {
	return m.recorder
}

// ListPhotosByEvent mocks base method.
func (m *MockPhotoStore) ListPhotosByEvent(ctx context.Context, eventID, filter, cursor string, limit int) ([]models.Photo, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPhotosByEvent", ctx, eventID, filter, cursor, limit)
	ret0, _ := ret[0].([]models.Photo)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPhotosByEvent indicates an expected call of ListPhotosByEvent.
func (mr *MockPhotoStoreMockRecorder) ListPhotosByEvent(ctx, eventID, filter, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPhotosByEvent",
		reflect.TypeOf((*MockPhotoStore)(nil).ListPhotosByEvent), ctx, eventID, filter, cursor, limit)
}
