// Code generated by MockGen. DO NOT EDIT.
// Source: handler (interfaces: PurchaseStore,PhotoStore,PhotoPresigner)
package mocks

import (
	"context"
	reflect "reflect"
	"time"

	gomock "github.com/golang/mock/gomock"
	models "github.com/racephotos/shared/models"
)

// MockPurchaseStore is a mock of PurchaseStore interface.
type MockPurchaseStore struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseStoreMockRecorder
}

type MockPurchaseStoreMockRecorder struct {
	mock *MockPurchaseStore
}

func NewMockPurchaseStore(ctrl *gomock.Controller) *MockPurchaseStore {
	mock := &MockPurchaseStore{ctrl: ctrl}
	mock.recorder = &MockPurchaseStoreMockRecorder{mock}
	return mock
}

func (m *MockPurchaseStore) EXPECT() *MockPurchaseStoreMockRecorder {
	return m.recorder
}

func (m *MockPurchaseStore) GetPurchaseByDownloadToken(ctx context.Context, token string) (*models.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchaseByDownloadToken", ctx, token)
	ret0, _ := ret[0].(*models.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPurchaseStoreMockRecorder) GetPurchaseByDownloadToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchaseByDownloadToken", reflect.TypeOf((*MockPurchaseStore)(nil).GetPurchaseByDownloadToken), ctx, token)
}

// MockPhotoStore is a mock of PhotoStore interface.
type MockPhotoStore struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoStoreMockRecorder
}

type MockPhotoStoreMockRecorder struct {
	mock *MockPhotoStore
}

func NewMockPhotoStore(ctrl *gomock.Controller) *MockPhotoStore {
	mock := &MockPhotoStore{ctrl: ctrl}
	mock.recorder = &MockPhotoStoreMockRecorder{mock}
	return mock
}

func (m *MockPhotoStore) EXPECT() *MockPhotoStoreMockRecorder {
	return m.recorder
}

func (m *MockPhotoStore) GetPhotoByID(ctx context.Context, photoID string) (*models.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotoByID", ctx, photoID)
	ret0, _ := ret[0].(*models.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPhotoStoreMockRecorder) GetPhotoByID(ctx, photoID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotoByID", reflect.TypeOf((*MockPhotoStore)(nil).GetPhotoByID), ctx, photoID)
}

// MockPhotoPresigner is a mock of PhotoPresigner interface.
type MockPhotoPresigner struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoPresignerMockRecorder
}

type MockPhotoPresignerMockRecorder struct {
	mock *MockPhotoPresigner
}

func NewMockPhotoPresigner(ctrl *gomock.Controller) *MockPhotoPresigner {
	mock := &MockPhotoPresigner{ctrl: ctrl}
	mock.recorder = &MockPhotoPresignerMockRecorder{mock}
	return mock
}

func (m *MockPhotoPresigner) EXPECT() *MockPhotoPresignerMockRecorder {
	return m.recorder
}

func (m *MockPhotoPresigner) PresignGetObject(ctx context.Context, bucket, key string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignGetObject", ctx, bucket, key, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPhotoPresignerMockRecorder) PresignGetObject(ctx, bucket, key, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignGetObject", reflect.TypeOf((*MockPhotoPresigner)(nil).PresignGetObject), ctx, bucket, key, ttl)
}
