// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/photo-processor/handler (interfaces: WatermarkQueue)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	models "github.com/racephotos/shared/models"
)

// MockWatermarkQueue is a mock of WatermarkQueue interface.
type MockWatermarkQueue struct {
	ctrl     *gomock.Controller
	recorder *MockWatermarkQueueMockRecorder
}

// MockWatermarkQueueMockRecorder is the mock recorder for MockWatermarkQueue.
type MockWatermarkQueueMockRecorder struct {
	mock *MockWatermarkQueue
}

// NewMockWatermarkQueue creates a new mock instance.
func NewMockWatermarkQueue(ctrl *gomock.Controller) *MockWatermarkQueue {
	mock := &MockWatermarkQueue{ctrl: ctrl}
	mock.recorder = &MockWatermarkQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatermarkQueue) EXPECT() *MockWatermarkQueueMockRecorder {
	return m.recorder
}

// SendWatermarkMessage mocks base method.
func (m *MockWatermarkQueue) SendWatermarkMessage(ctx context.Context, msg models.WatermarkMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWatermarkMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWatermarkMessage indicates an expected call of SendWatermarkMessage.
func (mr *MockWatermarkQueueMockRecorder) SendWatermarkMessage(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWatermarkMessage",
		reflect.TypeOf((*MockWatermarkQueue)(nil).SendWatermarkMessage), ctx, msg)
}
