// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/photo-processor/handler (interfaces: TextDetector)
package mocks

import (
	context "context"
	reflect "reflect"

	rekognition "github.com/aws/aws-sdk-go-v2/service/rekognition"
	gomock "github.com/golang/mock/gomock"
)

// MockTextDetector is a mock of TextDetector interface.
type MockTextDetector struct {
	ctrl     *gomock.Controller
	recorder *MockTextDetectorMockRecorder
}

// MockTextDetectorMockRecorder is the mock recorder for MockTextDetector.
type MockTextDetectorMockRecorder struct {
	mock *MockTextDetector
}

// NewMockTextDetector creates a new mock instance.
func NewMockTextDetector(ctrl *gomock.Controller) *MockTextDetector {
	mock := &MockTextDetector{ctrl: ctrl}
	mock.recorder = &MockTextDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextDetector) EXPECT() *MockTextDetectorMockRecorder {
	return m.recorder
}

// DetectText mocks base method.
func (m *MockTextDetector) DetectText(ctx context.Context, input *rekognition.DetectTextInput, optFns ...func(*rekognition.Options)) (*rekognition.DetectTextOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DetectText", varargs...)
	ret0, _ := ret[0].(*rekognition.DetectTextOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetectText indicates an expected call of DetectText.
func (mr *MockTextDetectorMockRecorder) DetectText(ctx, input interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectText",
		reflect.TypeOf((*MockTextDetector)(nil).DetectText), varargs...)
}
