// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/photo-processor/handler (interfaces: PhotoStore)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	models "github.com/racephotos/shared/models"
)

// MockPhotoStore is a mock of PhotoStore interface.
type MockPhotoStore struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoStoreMockRecorder
}

// MockPhotoStoreMockRecorder is the mock recorder for MockPhotoStore.
type MockPhotoStoreMockRecorder struct {
	mock *MockPhotoStore
}

// NewMockPhotoStore creates a new mock instance.
func NewMockPhotoStore(ctrl *gomock.Controller) *MockPhotoStore {
	mock := &MockPhotoStore{ctrl: ctrl}
	mock.recorder = &MockPhotoStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotoStore) EXPECT() *MockPhotoStoreMockRecorder {
	return m.recorder
}

// GetPhotoById mocks base method.
func (m *MockPhotoStore) GetPhotoById(ctx context.Context, id string) (*models.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotoById", ctx, id)
	ret0, _ := ret[0].(*models.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotoById indicates an expected call of GetPhotoById.
func (mr *MockPhotoStoreMockRecorder) GetPhotoById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotoById",
		reflect.TypeOf((*MockPhotoStore)(nil).GetPhotoById), ctx, id)
}

// UpdatePhotoStatus mocks base method.
func (m *MockPhotoStore) UpdatePhotoStatus(ctx context.Context, id string, update models.PhotoStatusUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePhotoStatus", ctx, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePhotoStatus indicates an expected call of UpdatePhotoStatus.
func (mr *MockPhotoStoreMockRecorder) UpdatePhotoStatus(ctx, id, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePhotoStatus",
		reflect.TypeOf((*MockPhotoStore)(nil).UpdatePhotoStatus), ctx, id, update)
}
