// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/get-photographer/handler (interfaces: PhotographerGetter)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	models "github.com/racephotos/shared/models"
)

// MockPhotographerGetter is a mock of PhotographerGetter interface.
type MockPhotographerGetter struct {
	ctrl     *gomock.Controller
	recorder *MockPhotographerGetterMockRecorder
}

// MockPhotographerGetterMockRecorder is the mock recorder for MockPhotographerGetter.
type MockPhotographerGetterMockRecorder struct {
	mock *MockPhotographerGetter
}

// NewMockPhotographerGetter creates a new mock instance.
func NewMockPhotographerGetter(ctrl *gomock.Controller) *MockPhotographerGetter {
	mock := &MockPhotographerGetter{ctrl: ctrl}
	mock.recorder = &MockPhotographerGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotographerGetter) EXPECT() *MockPhotographerGetterMockRecorder {
	return m.recorder
}

// GetPhotographer mocks base method.
func (m *MockPhotographerGetter) GetPhotographer(ctx context.Context, id string) (*models.Photographer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotographer", ctx, id)
	ret0, _ := ret[0].(*models.Photographer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotographer indicates an expected call of GetPhotographer.
func (mr *MockPhotographerGetterMockRecorder) GetPhotographer(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotographer",
		reflect.TypeOf((*MockPhotographerGetter)(nil).GetPhotographer), ctx, id)
}
