// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/search/handler (interfaces: PhotoStore)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	models "github.com/racephotos/shared/models"
)

// MockPhotoStore is a mock of PhotoStore interface.
type MockPhotoStore struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoStoreMockRecorder
}

// MockPhotoStoreMockRecorder is the mock recorder for MockPhotoStore.
type MockPhotoStoreMockRecorder struct {
	mock *MockPhotoStore
}

// NewMockPhotoStore creates a new mock instance.
func NewMockPhotoStore(ctrl *gomock.Controller) *MockPhotoStore {
	mock := &MockPhotoStore{ctrl: ctrl}
	mock.recorder = &MockPhotoStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotoStore) EXPECT() *MockPhotoStoreMockRecorder {
	return m.recorder
}

// BatchGetPhotos mocks base method.
func (m *MockPhotoStore) BatchGetPhotos(ctx context.Context, ids []string) ([]models.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetPhotos", ctx, ids)
	ret0, _ := ret[0].([]models.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetPhotos indicates an expected call of BatchGetPhotos.
func (mr *MockPhotoStoreMockRecorder) BatchGetPhotos(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetPhotos",
		reflect.TypeOf((*MockPhotoStore)(nil).BatchGetPhotos), ctx, ids)
}
