// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/search/handler (interfaces: BibIndexStore)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBibIndexStore is a mock of BibIndexStore interface.
type MockBibIndexStore struct {
	ctrl     *gomock.Controller
	recorder *MockBibIndexStoreMockRecorder
}

// MockBibIndexStoreMockRecorder is the mock recorder for MockBibIndexStore.
type MockBibIndexStoreMockRecorder struct {
	mock *MockBibIndexStore
}

// NewMockBibIndexStore creates a new mock instance.
func NewMockBibIndexStore(ctrl *gomock.Controller) *MockBibIndexStore {
	mock := &MockBibIndexStore{ctrl: ctrl}
	mock.recorder = &MockBibIndexStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBibIndexStore) EXPECT() *MockBibIndexStoreMockRecorder {
	return m.recorder
}

// GetPhotoIDsByBib mocks base method.
func (m *MockBibIndexStore) GetPhotoIDsByBib(ctx context.Context, eventID, bibNumber string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotoIDsByBib", ctx, eventID, bibNumber)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotoIDsByBib indicates an expected call of GetPhotoIDsByBib.
func (mr *MockBibIndexStoreMockRecorder) GetPhotoIDsByBib(ctx, eventID, bibNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotoIDsByBib",
		reflect.TypeOf((*MockBibIndexStore)(nil).GetPhotoIDsByBib), ctx, eventID, bibNumber)
}
