// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/list-photographer-events/handler (interfaces: EventLister)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	models "github.com/racephotos/shared/models"
)

// MockEventLister is a mock of EventLister interface.
type MockEventLister struct {
	ctrl     *gomock.Controller
	recorder *MockEventListerMockRecorder
}

// MockEventListerMockRecorder is the mock recorder for MockEventLister.
type MockEventListerMockRecorder struct {
	mock *MockEventLister
}

// NewMockEventLister creates a new mock instance.
func NewMockEventLister(ctrl *gomock.Controller) *MockEventLister {
	mock := &MockEventLister{ctrl: ctrl}
	mock.recorder = &MockEventListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventLister) EXPECT() *MockEventListerMockRecorder {
	return m.recorder
}

// ListEventsByPhotographer mocks base method.
func (m *MockEventLister) ListEventsByPhotographer(ctx context.Context, photographerID, cursor string, limit int) ([]models.Event, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEventsByPhotographer", ctx, photographerID, cursor, limit)
	ret0, _ := ret[0].([]models.Event)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEventsByPhotographer indicates an expected call of ListEventsByPhotographer.
func (mr *MockEventListerMockRecorder) ListEventsByPhotographer(ctx, photographerID, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEventsByPhotographer",
		reflect.TypeOf((*MockEventLister)(nil).ListEventsByPhotographer), ctx, photographerID, cursor, limit)
}
