// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/presign-photos/handler (interfaces: PhotoStore)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	models "github.com/racephotos/shared/models"
)

// MockPhotoStore is a mock of PhotoStore interface.
type MockPhotoStore struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoStoreMockRecorder
}

// MockPhotoStoreMockRecorder is the mock recorder for MockPhotoStore.
type MockPhotoStoreMockRecorder struct {
	mock *MockPhotoStore
}

// NewMockPhotoStore creates a new mock instance.
func NewMockPhotoStore(ctrl *gomock.Controller) *MockPhotoStore {
	mock := &MockPhotoStore{ctrl: ctrl}
	mock.recorder = &MockPhotoStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotoStore) EXPECT() *MockPhotoStoreMockRecorder {
	return m.recorder
}

// BatchCreatePhotos mocks base method.
func (m *MockPhotoStore) BatchCreatePhotos(ctx context.Context, photos []models.Photo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreatePhotos", ctx, photos)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreatePhotos indicates an expected call of BatchCreatePhotos.
func (mr *MockPhotoStoreMockRecorder) BatchCreatePhotos(ctx, photos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreatePhotos",
		reflect.TypeOf((*MockPhotoStore)(nil).BatchCreatePhotos), ctx, photos)
}
