// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/presign-photos/handler (interfaces: S3Presigner)
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockS3Presigner is a mock of S3Presigner interface.
type MockS3Presigner struct {
	ctrl     *gomock.Controller
	recorder *MockS3PresignerMockRecorder
}

// MockS3PresignerMockRecorder is the mock recorder for MockS3Presigner.
type MockS3PresignerMockRecorder struct {
	mock *MockS3Presigner
}

// NewMockS3Presigner creates a new mock instance.
func NewMockS3Presigner(ctrl *gomock.Controller) *MockS3Presigner {
	mock := &MockS3Presigner{ctrl: ctrl}
	mock.recorder = &MockS3PresignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Presigner) EXPECT() *MockS3PresignerMockRecorder {
	return m.recorder
}

// PresignPutObject mocks base method.
func (m *MockS3Presigner) PresignPutObject(ctx context.Context, bucket, key, contentType string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignPutObject", ctx, bucket, key, contentType, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignPutObject indicates an expected call of PresignPutObject.
func (mr *MockS3PresignerMockRecorder) PresignPutObject(ctx, bucket, key, contentType, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignPutObject",
		reflect.TypeOf((*MockS3Presigner)(nil).PresignPutObject), ctx, bucket, key, contentType, ttl)
}
