// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/watermark/handler (interfaces: ProcessedPhotoWriter)
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProcessedPhotoWriter is a mock of ProcessedPhotoWriter interface.
type MockProcessedPhotoWriter struct {
	ctrl     *gomock.Controller
	recorder *MockProcessedPhotoWriterMockRecorder
}

// MockProcessedPhotoWriterMockRecorder is the mock recorder for MockProcessedPhotoWriter.
type MockProcessedPhotoWriterMockRecorder struct {
	mock *MockProcessedPhotoWriter
}

// NewMockProcessedPhotoWriter creates a new mock instance.
func NewMockProcessedPhotoWriter(ctrl *gomock.Controller) *MockProcessedPhotoWriter {
	mock := &MockProcessedPhotoWriter{ctrl: ctrl}
	mock.recorder = &MockProcessedPhotoWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessedPhotoWriter) EXPECT() *MockProcessedPhotoWriterMockRecorder {
	return m.recorder
}

// PutObject mocks base method.
func (m *MockProcessedPhotoWriter) PutObject(ctx context.Context, bucket, key string, body io.Reader, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, bucket, key, body, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockProcessedPhotoWriterMockRecorder) PutObject(ctx, bucket, key, body, contentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject",
		reflect.TypeOf((*MockProcessedPhotoWriter)(nil).PutObject), ctx, bucket, key, body, contentType)
}
