// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/watermark/handler (interfaces: RawPhotoReader)
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRawPhotoReader is a mock of RawPhotoReader interface.
type MockRawPhotoReader struct {
	ctrl     *gomock.Controller
	recorder *MockRawPhotoReaderMockRecorder
}

// MockRawPhotoReaderMockRecorder is the mock recorder for MockRawPhotoReader.
type MockRawPhotoReaderMockRecorder struct {
	mock *MockRawPhotoReader
}

// NewMockRawPhotoReader creates a new mock instance.
func NewMockRawPhotoReader(ctrl *gomock.Controller) *MockRawPhotoReader {
	mock := &MockRawPhotoReader{ctrl: ctrl}
	mock.recorder = &MockRawPhotoReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRawPhotoReader) EXPECT() *MockRawPhotoReaderMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *MockRawPhotoReader) GetObject(ctx context.Context, bucket, key string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, bucket, key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockRawPhotoReaderMockRecorder) GetObject(ctx, bucket, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject",
		reflect.TypeOf((*MockRawPhotoReader)(nil).GetObject), ctx, bucket, key)
}
