// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/watermark/handler (interfaces: EventCountUpdater)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEventCountUpdater is a mock of EventCountUpdater interface.
type MockEventCountUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockEventCountUpdaterMockRecorder
}

// MockEventCountUpdaterMockRecorder is the mock recorder for MockEventCountUpdater.
type MockEventCountUpdaterMockRecorder struct {
	mock *MockEventCountUpdater
}

// NewMockEventCountUpdater creates a new mock instance.
func NewMockEventCountUpdater(ctrl *gomock.Controller) *MockEventCountUpdater {
	mock := &MockEventCountUpdater{ctrl: ctrl}
	mock.recorder = &MockEventCountUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventCountUpdater) EXPECT() *MockEventCountUpdaterMockRecorder {
	return m.recorder
}

// IncrementPhotoCount mocks base method.
func (m *MockEventCountUpdater) IncrementPhotoCount(ctx context.Context, eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementPhotoCount", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementPhotoCount indicates an expected call of IncrementPhotoCount.
func (mr *MockEventCountUpdaterMockRecorder) IncrementPhotoCount(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementPhotoCount",
		reflect.TypeOf((*MockEventCountUpdater)(nil).IncrementPhotoCount), ctx, eventID)
}
