// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/watermark/handler (interfaces: ImageWatermarker)
package mocks

import (
	image "image"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockImageWatermarker is a mock of ImageWatermarker interface.
type MockImageWatermarker struct {
	ctrl     *gomock.Controller
	recorder *MockImageWatermarkerMockRecorder
}

// MockImageWatermarkerMockRecorder is the mock recorder for MockImageWatermarker.
type MockImageWatermarkerMockRecorder struct {
	mock *MockImageWatermarker
}

// NewMockImageWatermarker creates a new mock instance.
func NewMockImageWatermarker(ctrl *gomock.Controller) *MockImageWatermarker {
	mock := &MockImageWatermarker{ctrl: ctrl}
	mock.recorder = &MockImageWatermarkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageWatermarker) EXPECT() *MockImageWatermarkerMockRecorder {
	return m.recorder
}

// ApplyTextWatermark mocks base method.
func (m *MockImageWatermarker) ApplyTextWatermark(src io.Reader, text string) (image.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyTextWatermark", src, text)
	ret0, _ := ret[0].(image.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyTextWatermark indicates an expected call of ApplyTextWatermark.
func (mr *MockImageWatermarkerMockRecorder) ApplyTextWatermark(src, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyTextWatermark",
		reflect.TypeOf((*MockImageWatermarker)(nil).ApplyTextWatermark), src, text)
}
