// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/watermark/handler (interfaces: EventStore)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEventStore is a mock of EventStore interface.
type MockEventStore struct {
	ctrl     *gomock.Controller
	recorder *MockEventStoreMockRecorder
}

// MockEventStoreMockRecorder is the mock recorder for MockEventStore.
type MockEventStoreMockRecorder struct {
	mock *MockEventStore
}

// NewMockEventStore creates a new mock instance.
func NewMockEventStore(ctrl *gomock.Controller) *MockEventStore {
	mock := &MockEventStore{ctrl: ctrl}
	mock.recorder = &MockEventStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStore) EXPECT() *MockEventStoreMockRecorder {
	return m.recorder
}

// GetWatermarkText mocks base method.
func (m *MockEventStore) GetWatermarkText(ctx context.Context, eventId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWatermarkText", ctx, eventId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWatermarkText indicates an expected call of GetWatermarkText.
func (mr *MockEventStoreMockRecorder) GetWatermarkText(ctx, eventId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatermarkText",
		reflect.TypeOf((*MockEventStore)(nil).GetWatermarkText), ctx, eventId)
}
