// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/watermark/handler (interfaces: PhotoStore)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPhotoStore is a mock of PhotoStore interface.
type MockPhotoStore struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoStoreMockRecorder
}

// MockPhotoStoreMockRecorder is the mock recorder for MockPhotoStore.
type MockPhotoStoreMockRecorder struct {
	mock *MockPhotoStore
}

// NewMockPhotoStore creates a new mock instance.
func NewMockPhotoStore(ctrl *gomock.Controller) *MockPhotoStore {
	mock := &MockPhotoStore{ctrl: ctrl}
	mock.recorder = &MockPhotoStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotoStore) EXPECT() *MockPhotoStoreMockRecorder {
	return m.recorder
}

// UpdateWatermarkedKey mocks base method.
func (m *MockPhotoStore) UpdateWatermarkedKey(ctx context.Context, photoId, watermarkedS3Key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWatermarkedKey", ctx, photoId, watermarkedS3Key)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWatermarkedKey indicates an expected call of UpdateWatermarkedKey.
func (mr *MockPhotoStoreMockRecorder) UpdateWatermarkedKey(ctx, photoId, watermarkedS3Key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWatermarkedKey",
		reflect.TypeOf((*MockPhotoStore)(nil).UpdateWatermarkedKey), ctx, photoId, watermarkedS3Key)
}
