// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/racephotos/update-photographer/handler (interfaces: PhotographerUpserter)
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/racephotos/shared/models"
)

// MockPhotographerUpserter is a mock of PhotographerUpserter interface.
type MockPhotographerUpserter struct {
	ctrl     *gomock.Controller
	recorder *MockPhotographerUpserterMockRecorder
}

// MockPhotographerUpserterMockRecorder is the mock recorder for MockPhotographerUpserter.
type MockPhotographerUpserterMockRecorder struct {
	mock *MockPhotographerUpserter
}

// NewMockPhotographerUpserter creates a new mock instance.
func NewMockPhotographerUpserter(ctrl *gomock.Controller) *MockPhotographerUpserter {
	mock := &MockPhotographerUpserter{ctrl: ctrl}
	mock.recorder = &MockPhotographerUpserterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotographerUpserter) EXPECT() *MockPhotographerUpserterMockRecorder {
	return m.recorder
}

// UpsertPhotographer mocks base method.
func (m *MockPhotographerUpserter) UpsertPhotographer(ctx context.Context, p models.Photographer) (*models.Photographer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPhotographer", ctx, p)
	ret0, _ := ret[0].(*models.Photographer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertPhotographer indicates an expected call of UpsertPhotographer.
func (mr *MockPhotographerUpserterMockRecorder) UpsertPhotographer(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPhotographer",
		reflect.TypeOf((*MockPhotographerUpserter)(nil).UpsertPhotographer), ctx, p)
}
