import * as cdk from 'aws-cdk-lib';
import * as cloudwatch from 'aws-cdk-lib/aws-cloudwatch';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import { Construct } from 'constructs';

export interface ObservabilityProps {
  /** The Lambda function to instrument. */
  lambda: lambda.Function;
  /**
   * Log retention in days.
   * Pass EnvConfig.photoRetentionDays — keeps log retention in sync with
   * the photo lifecycle so operators aren't paying for logs longer than photos exist.
   */
  logRetentionDays: number;
  /**
   * DLQ to monitor. When provided, a CloudWatch Alarm fires when
   * ApproximateNumberOfMessagesVisible >= 1 in any 5-minute window.
   *
   * Required for every SQS-triggered Lambda (CLAUDE.md mandate).
   * Omit only for non-SQS Lambdas (e.g. API Gateway-triggered).
   */
  dlq?: sqs.Queue;
}

/**
 * ObservabilityConstruct
 *
 * Wraps a Lambda function with the standard RaceShots observability stack:
 *   - X-Ray active tracing (AWS_XRAY_TRACING_NAME env var set automatically by CDK)
 *   - CloudWatch Log Group with explicit retention (no unbounded accumulation)
 *   - CloudWatch Alarm: Lambda Errors ≥ 1 over a 5-minute window
 *   - CloudWatch Alarm: DLQ depth ≥ 1 (when dlq prop is provided)
 *
 * Usage (one line per Lambda construct):
 *
 *   new ObservabilityConstruct(this, 'Observability', {
 *     lambda: myFn,
 *     logRetentionDays: config.photoRetentionDays,
 *     dlq: myDlq,   // omit for non-SQS Lambdas
 *   });
 *
 * See docs/adr/0008-observability-strategy.md for rationale.
 */
export class ObservabilityConstruct extends Construct {
  /** CloudWatch Alarm that fires on any Lambda Errors. */
  readonly errorAlarm: cloudwatch.Alarm;
  /** CloudWatch Alarm that fires when the DLQ has ≥ 1 message (only set when dlq provided). */
  readonly dlqAlarm?: cloudwatch.Alarm;
  /** The managed CloudWatch Log Group for the Lambda. */
  readonly logGroup: logs.LogGroup;

  constructor(scope: Construct, id: string, props: ObservabilityProps) {
    super(scope, id);

    const { lambda: fn, logRetentionDays, dlq } = props;

    // ── X-Ray active tracing ──────────────────────────────────────────────
    // Sets ACTIVE mode: Lambda traces every invocation and propagates the
    // trace context to downstream AWS SDK calls (S3, DynamoDB, SQS, Rekognition).
    // No code instrumentation required — the X-Ray SDK auto-patches AWS SDK v3.
    //
    // The `tracing` property is not mutable after Lambda construction, so we
    // override the underlying L1 CfnFunction's TracingConfig directly.
    fn.addEnvironment('AWS_XRAY_CONTEXT_MISSING', 'LOG_ERROR');
    const cfnFn = fn.node.defaultChild as lambda.CfnFunction;
    cfnFn.tracingConfig = { mode: 'Active' };

    // ── Log Group with retention ──────────────────────────────────────────
    // CDK creates a default log group for every Lambda, but without a retention
    // policy it accumulates indefinitely. We create the log group explicitly with
    // a retention window that mirrors the photo lifecycle (photoRetentionDays).
    //
    // removalPolicy: DESTROY — log data is not authoritative; it can be
    // regenerated by re-running the Lambda. This keeps dev environments clean.
    this.logGroup = new logs.LogGroup(this, 'LogGroup', {
      logGroupName: `/aws/lambda/${fn.functionName}`,
      retention: this.toRetentionDays(logRetentionDays),
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    // ── Lambda error alarm ────────────────────────────────────────────────
    // Fires as soon as a single Lambda error occurs in a 5-minute window.
    // Threshold: 1 error — Lambda errors are unexpected in normal operation;
    // any non-zero count warrants investigation.
    this.errorAlarm = new cloudwatch.Alarm(this, 'ErrorAlarm', {
      alarmName: `${fn.functionName}-errors`,
      alarmDescription: `Lambda ${fn.functionName} has >= 1 error in a 5-minute window`,
      metric: fn.metricErrors({
        period: cdk.Duration.minutes(5),
        statistic: 'Sum',
      }),
      threshold: 1,
      evaluationPeriods: 1,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    });

    // ── DLQ depth alarm ───────────────────────────────────────────────────
    // Required for all SQS-triggered Lambdas (CLAUDE.md mandate).
    // A message in the DLQ means the processor failed maxReceiveCount times —
    // this is always a production incident requiring immediate attention.
    if (dlq) {
      this.dlqAlarm = new cloudwatch.Alarm(this, 'DlqAlarm', {
        alarmName: `${fn.functionName}-dlq-depth`,
        alarmDescription: `DLQ for ${fn.functionName} has >= 1 message — processing failure detected`,
        metric: dlq.metricApproximateNumberOfMessagesVisible({
          period: cdk.Duration.minutes(5),
          statistic: 'Maximum',
        }),
        threshold: 1,
        evaluationPeriods: 1,
        comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
        treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
      });
    }
  }

  /**
   * Maps an arbitrary number of days to the nearest CloudWatch Logs RetentionDays enum value.
   * CloudWatch only accepts specific retention periods — this method rounds up to the next
   * supported value so log data is never discarded earlier than the configured window.
   */
  private toRetentionDays(days: number): logs.RetentionDays {
    // Ordered from smallest to largest — return the first value >= requested days.
    const supported: [number, logs.RetentionDays][] = [
      [1, logs.RetentionDays.ONE_DAY],
      [3, logs.RetentionDays.THREE_DAYS],
      [5, logs.RetentionDays.FIVE_DAYS],
      [7, logs.RetentionDays.ONE_WEEK],
      [14, logs.RetentionDays.TWO_WEEKS],
      [30, logs.RetentionDays.ONE_MONTH],
      [60, logs.RetentionDays.TWO_MONTHS],
      [90, logs.RetentionDays.THREE_MONTHS],
      [120, logs.RetentionDays.FOUR_MONTHS],
      [150, logs.RetentionDays.FIVE_MONTHS],
      [180, logs.RetentionDays.SIX_MONTHS],
      [365, logs.RetentionDays.ONE_YEAR],
      [400, logs.RetentionDays.THIRTEEN_MONTHS],
      [545, logs.RetentionDays.EIGHTEEN_MONTHS],
      [731, logs.RetentionDays.TWO_YEARS],
      [1096, logs.RetentionDays.THREE_YEARS],
      [1827, logs.RetentionDays.FIVE_YEARS],
      [2557, logs.RetentionDays.SEVEN_YEARS],
      [3653, logs.RetentionDays.TEN_YEARS],
    ];

    for (const [threshold, retention] of supported) {
      if (days <= threshold) return retention;
    }

    return logs.RetentionDays.TEN_YEARS;
  }
}
